import { CheckerAction, type SyntaxTableEntry } from "@src/interface/visitor/SyntaxChecker";
import { ComposedTokenType, TokenType } from "@src/interface/visitor/Token";

export const SYNTAX_TABLE_ACC: Array<Record<TokenType | ComposedTokenType, SyntaxTableEntry>> = [
    {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, },
        [TokenType.LABEL]: { type: CheckerAction.ERROR, },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.SHIFT, number: 10 },
        [TokenType.DATA_LABEL]: { type: CheckerAction.ERROR, },
        [TokenType.NUMBER]: { type: CheckerAction.ERROR, },
        [TokenType.OPERATION]: { type: CheckerAction.ERROR, },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, },
        [TokenType.WORD]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.DATA]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.SHIFT, number: 1 },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.TEXT]: { type: CheckerAction.SHIFT, number: 2 },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.ERROR, },
    },
    {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, },
        [TokenType.LABEL]: { type: CheckerAction.ERROR, },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.ERROR, },
        [TokenType.DATA_LABEL]: { type: CheckerAction.ERROR, },
        [TokenType.NUMBER]: { type: CheckerAction.ERROR, },
        [TokenType.OPERATION]: { type: CheckerAction.ERROR, },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, },
        [TokenType.WORD]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.DATA]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.TEXT]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.ACCEPT, },
    },
    {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, },
        [TokenType.LABEL]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.PROGRAM_DATA },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.PROGRAM_DATA },
        [TokenType.DATA_LABEL]: { type: CheckerAction.SHIFT, number: 5 },
        [TokenType.NUMBER]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.PROGRAM_DATA },
        [TokenType.OPERATION]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.PROGRAM_DATA },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, },
        [TokenType.WORD]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.PROGRAM_DATA },
        [ComposedTokenType.DATA]: { type: CheckerAction.SHIFT, number: 4 },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.SHIFT, number: 3 },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.TEXT]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.PROGRAM_DATA },
    },
    {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, },
        [TokenType.LABEL]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.PROGRAM },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.PROGRAM },
        [TokenType.DATA_LABEL]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.PROGRAM },
        [TokenType.NUMBER]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.PROGRAM },
        [TokenType.OPERATION]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.PROGRAM },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, },
        [TokenType.WORD]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.PROGRAM },
        [ComposedTokenType.DATA]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.TEXT]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.PROGRAM },
    },
    {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, },
        [TokenType.LABEL]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.PROGRAM_DATA },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.PROGRAM_DATA },
        [TokenType.DATA_LABEL]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.PROGRAM_DATA },
        [TokenType.NUMBER]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.PROGRAM_DATA },
        [TokenType.OPERATION]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.PROGRAM_DATA },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, },
        [TokenType.WORD]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.PROGRAM_DATA },
        [ComposedTokenType.DATA]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.TEXT]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.PROGRAM_DATA },
    },
    {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, },
        [TokenType.LABEL]: { type: CheckerAction.SHIFT, number: 6 },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [TokenType.DATA_LABEL]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [TokenType.NUMBER]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [TokenType.OPERATION]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, },
        [TokenType.WORD]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [ComposedTokenType.DATA]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.SHIFT, number: 7 },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.TEXT]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.DATA_BLOCK },
    },
    {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, },
        [TokenType.LABEL]: { type: CheckerAction.ERROR, },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.ERROR, },
        [TokenType.DATA_LABEL]: { type: CheckerAction.ERROR, },
        [TokenType.NUMBER]: { type: CheckerAction.SHIFT, number: 8 },
        [TokenType.OPERATION]: { type: CheckerAction.ERROR, },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, },
        [TokenType.WORD]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.DATA]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.TEXT]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.ERROR, },
    },
    {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, },
        [TokenType.LABEL]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.DATA },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.DATA },
        [TokenType.DATA_LABEL]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.DATA },
        [TokenType.NUMBER]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.DATA },
        [TokenType.OPERATION]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.DATA },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, },
        [TokenType.WORD]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.DATA },
        [ComposedTokenType.DATA]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.TEXT]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.DATA },
    },
    {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, },
        [TokenType.LABEL]: { type: CheckerAction.SHIFT, number: 6 },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [TokenType.DATA_LABEL]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [TokenType.NUMBER]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [TokenType.OPERATION]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, },
        [TokenType.WORD]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [ComposedTokenType.DATA]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.SHIFT, number: 9 },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.TEXT]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.DATA_BLOCK },
    },
    {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, },
        [TokenType.LABEL]: { type: CheckerAction.REDUCE, number: 3, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.REDUCE, number: 3, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [TokenType.DATA_LABEL]: { type: CheckerAction.REDUCE, number: 3, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [TokenType.NUMBER]: { type: CheckerAction.REDUCE, number: 3, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [TokenType.OPERATION]: { type: CheckerAction.REDUCE, number: 3, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, },
        [TokenType.WORD]: { type: CheckerAction.REDUCE, number: 3, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [ComposedTokenType.DATA]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.TEXT]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.REDUCE, number: 3, reducedAddition: ComposedTokenType.DATA_BLOCK },
    },
    {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, },
        [TokenType.LABEL]: { type: CheckerAction.SHIFT, number: 13 },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.TEXT_BLOCK },
        [TokenType.DATA_LABEL]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.TEXT_BLOCK },
        [TokenType.NUMBER]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.TEXT_BLOCK },
        [TokenType.OPERATION]: { type: CheckerAction.SHIFT, number: 14 },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, },
        [TokenType.WORD]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.TEXT_BLOCK },
        [ComposedTokenType.DATA]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.SHIFT, number: 12 },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.SHIFT, number: 16 },
        [ComposedTokenType.TEXT]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.SHIFT, number: 11 },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.TEXT_BLOCK },
    },
    {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, },
        [TokenType.LABEL]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.TEXT },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.TEXT },
        [TokenType.DATA_LABEL]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.TEXT },
        [TokenType.NUMBER]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.TEXT },
        [TokenType.OPERATION]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.TEXT },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, },
        [TokenType.WORD]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.TEXT },
        [ComposedTokenType.DATA]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.TEXT]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.TEXT },
    },
    {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, },
        [TokenType.LABEL]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.STATEMENT },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.STATEMENT },
        [TokenType.DATA_LABEL]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.STATEMENT },
        [TokenType.NUMBER]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.STATEMENT },
        [TokenType.OPERATION]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.STATEMENT },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, },
        [TokenType.WORD]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.STATEMENT },
        [ComposedTokenType.DATA]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.TEXT]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.STATEMENT },
    },
    {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, },
        [TokenType.LABEL]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.STATEMENT },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.STATEMENT },
        [TokenType.DATA_LABEL]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.STATEMENT },
        [TokenType.NUMBER]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.STATEMENT },
        [TokenType.OPERATION]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.STATEMENT },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, },
        [TokenType.WORD]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.STATEMENT },
        [ComposedTokenType.DATA]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.TEXT]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.STATEMENT },
    },
    {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, },
        [TokenType.LABEL]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.INSTRUCTION },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.INSTRUCTION },
        [TokenType.DATA_LABEL]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.INSTRUCTION },
        [TokenType.NUMBER]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.INSTRUCTION },
        [TokenType.OPERATION]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.INSTRUCTION },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, },
        [TokenType.WORD]: { type: CheckerAction.SHIFT, number: 15 },
        [ComposedTokenType.DATA]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.TEXT]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.INSTRUCTION },
    },
    {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, },
        [TokenType.LABEL]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.INSTRUCTION },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.INSTRUCTION },
        [TokenType.DATA_LABEL]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.INSTRUCTION },
        [TokenType.NUMBER]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.INSTRUCTION },
        [TokenType.OPERATION]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.INSTRUCTION },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, },
        [TokenType.WORD]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.INSTRUCTION },
        [ComposedTokenType.DATA]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.TEXT]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.INSTRUCTION },
    },
    {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, },
        [TokenType.LABEL]: { type: CheckerAction.SHIFT, number: 13 },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.TEXT_BLOCK },
        [TokenType.DATA_LABEL]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.TEXT_BLOCK },
        [TokenType.NUMBER]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.TEXT_BLOCK },
        [TokenType.OPERATION]: { type: CheckerAction.SHIFT, number: 14 },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, },
        [TokenType.WORD]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.TEXT_BLOCK },
        [ComposedTokenType.DATA]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.SHIFT, number: 12 },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.SHIFT, number: 16 },
        [ComposedTokenType.TEXT]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.SHIFT, number: 17 },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.TEXT_BLOCK },
    },
    {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, },
        [TokenType.LABEL]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.TEXT_BLOCK },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.TEXT_BLOCK },
        [TokenType.DATA_LABEL]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.TEXT_BLOCK },
        [TokenType.NUMBER]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.TEXT_BLOCK },
        [TokenType.OPERATION]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.TEXT_BLOCK },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, },
        [TokenType.WORD]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.TEXT_BLOCK },
        [ComposedTokenType.DATA]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.TEXT]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.ERROR, },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.TEXT_BLOCK },
    },
];