import { RiscTokenType } from "@src/interface/visitor/Token";
import { RiscSyntaxState } from "./SyntaxCheckerState";
import type { SyntaxTableEntry } from "@src/interface/visitor/SyntaxChecker";
import { CheckerAction } from "@src/interface/visitor/SyntaxChecker";
import { JUMP_LABEL, LDI_IMMEDIATE, LOGIC_ERROR, OPERATION_REGISTER } from "./ErrorAndWarning";

export const RISC_SYNTAX_TABLE: Record<RiscSyntaxState, Record<RiscTokenType, SyntaxTableEntry>> = {
    [RiscSyntaxState.INITIAL]: {
        [RiscTokenType.NO_ARGS]: { type: CheckerAction.SHIFT, number: RiscSyntaxState.NO_ARGS_OPERATION },
        [RiscTokenType.TWO_REG]: { type: CheckerAction.SHIFT, number: RiscSyntaxState.TWO_REG_OPERATION },
        [RiscTokenType.THREE_REG]: { type: CheckerAction.SHIFT, number: RiscSyntaxState.THREE_REG_OPERATION },
        [RiscTokenType.JUMP]: { type: CheckerAction.SHIFT, number: RiscSyntaxState.JUMP_OPERATION },
        [RiscTokenType.IMM_LOAD]: { type: CheckerAction.SHIFT, number: RiscSyntaxState.IMM_LOAD_OPERATION },
        [RiscTokenType.STORE]: { type: CheckerAction.SHIFT, number: RiscSyntaxState.STORE_OPERATION },
        [RiscTokenType.LOAD]: { type: CheckerAction.SHIFT, number: RiscSyntaxState.LOAD_OPERATION },
        [RiscTokenType.NUMBER]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [RiscTokenType.REGISTER]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [RiscTokenType.LABEL]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [RiscTokenType.INSTRUCTION]: { type: CheckerAction.SHIFT, number: RiscSyntaxState.EXIT },
        [RiscTokenType.ARGUMENTS]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [RiscTokenType.OTHER]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
    },
    [RiscSyntaxState.OPERATION_REDUCE]: {
        [RiscTokenType.NO_ARGS]: { type: CheckerAction.REDUCE, number: 2 },
        [RiscTokenType.TWO_REG]: { type: CheckerAction.REDUCE, number: 2 },
        [RiscTokenType.THREE_REG]: { type: CheckerAction.REDUCE, number: 2 },
        [RiscTokenType.JUMP]: { type: CheckerAction.REDUCE, number: 2 },
        [RiscTokenType.IMM_LOAD]: { type: CheckerAction.REDUCE, number: 2 },
        [RiscTokenType.STORE]: { type: CheckerAction.REDUCE, number: 2 },
        [RiscTokenType.LOAD]: { type: CheckerAction.REDUCE, number: 2 },
        [RiscTokenType.NUMBER]: { type: CheckerAction.REDUCE, number: 2 },
        [RiscTokenType.REGISTER]: { type: CheckerAction.REDUCE, number: 2 },
        [RiscTokenType.LABEL]: { type: CheckerAction.REDUCE, number: 2 },
        [RiscTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [RiscTokenType.ARGUMENTS]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [RiscTokenType.OTHER]: { type: CheckerAction.REDUCE, number: 2 },
    },
    [RiscSyntaxState.EXIT]: {
        [RiscTokenType.NO_ARGS]: { type: CheckerAction.ACCEPT, },
        [RiscTokenType.TWO_REG]: { type: CheckerAction.ACCEPT, },
        [RiscTokenType.THREE_REG]: { type: CheckerAction.ACCEPT, },
        [RiscTokenType.JUMP]: { type: CheckerAction.ACCEPT, },
        [RiscTokenType.IMM_LOAD]: { type: CheckerAction.ACCEPT, },
        [RiscTokenType.STORE]: { type: CheckerAction.ACCEPT, },
        [RiscTokenType.LOAD]: { type: CheckerAction.ACCEPT, },
        [RiscTokenType.NUMBER]: { type: CheckerAction.ACCEPT, },
        [RiscTokenType.REGISTER]: { type: CheckerAction.ACCEPT, },
        [RiscTokenType.LABEL]: { type: CheckerAction.ACCEPT, },
        [RiscTokenType.INSTRUCTION]: { type: CheckerAction.ACCEPT, },
        [RiscTokenType.ARGUMENTS]: { type: CheckerAction.ACCEPT, },
        [RiscTokenType.OTHER]: { type: CheckerAction.ACCEPT, },
    },
    [RiscSyntaxState.JUMP_OPERATION]: {
        [RiscTokenType.NO_ARGS]: { type: CheckerAction.ERROR, message: JUMP_LABEL },
        [RiscTokenType.TWO_REG]: { type: CheckerAction.ERROR, message: JUMP_LABEL },
        [RiscTokenType.THREE_REG]: { type: CheckerAction.ERROR, message: JUMP_LABEL },
        [RiscTokenType.JUMP]: { type: CheckerAction.ERROR, message: JUMP_LABEL },
        [RiscTokenType.IMM_LOAD]: { type: CheckerAction.ERROR, message: JUMP_LABEL },
        [RiscTokenType.STORE]: { type: CheckerAction.ERROR, message: JUMP_LABEL },
        [RiscTokenType.LOAD]: { type: CheckerAction.ERROR, message: JUMP_LABEL },
        [RiscTokenType.NUMBER]: { type: CheckerAction.ERROR, message: JUMP_LABEL },
        [RiscTokenType.REGISTER]: { type: CheckerAction.ERROR, message: JUMP_LABEL },
        [RiscTokenType.LABEL]: { type: CheckerAction.SHIFT, number: RiscSyntaxState.LABEL_ARGS },
        [RiscTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [RiscTokenType.ARGUMENTS]: { type: CheckerAction.SHIFT, number: RiscSyntaxState.OPERATION_REDUCE },
        [RiscTokenType.OTHER]: { type: CheckerAction.ERROR, message: JUMP_LABEL },
    },
    [RiscSyntaxState.TWO_REG_OPERATION]: {
        [RiscTokenType.NO_ARGS]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.TWO_REG]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.THREE_REG]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.JUMP]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.IMM_LOAD]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.STORE]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.LOAD]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.NUMBER]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.REGISTER]: { type: CheckerAction.SHIFT, number: RiscSyntaxState.TWO_REG_FIRST_REG },
        [RiscTokenType.LABEL]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [RiscTokenType.ARGUMENTS]: { type: CheckerAction.SHIFT, number: RiscSyntaxState.OPERATION_REDUCE },
        [RiscTokenType.OTHER]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
    },
    [RiscSyntaxState.THREE_REG_OPERATION]: {
        [RiscTokenType.NO_ARGS]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.TWO_REG]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.THREE_REG]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.JUMP]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.IMM_LOAD]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.STORE]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.LOAD]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.NUMBER]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.REGISTER]: { type: CheckerAction.SHIFT, number: RiscSyntaxState.THREE_REG_FIRST_REG },
        [RiscTokenType.LABEL]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [RiscTokenType.ARGUMENTS]: { type: CheckerAction.SHIFT, number: RiscSyntaxState.OPERATION_REDUCE },
        [RiscTokenType.OTHER]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
    },
    [RiscSyntaxState.LABEL_ARGS]: {
        [RiscTokenType.NO_ARGS]: { type: CheckerAction.REDUCE, number: 1 },
        [RiscTokenType.TWO_REG]: { type: CheckerAction.REDUCE, number: 1 },
        [RiscTokenType.THREE_REG]: { type: CheckerAction.REDUCE, number: 1 },
        [RiscTokenType.JUMP]: { type: CheckerAction.REDUCE, number: 1 },
        [RiscTokenType.IMM_LOAD]: { type: CheckerAction.REDUCE, number: 1 },
        [RiscTokenType.STORE]: { type: CheckerAction.REDUCE, number: 1 },
        [RiscTokenType.LOAD]: { type: CheckerAction.REDUCE, number: 1 },
        [RiscTokenType.NUMBER]: { type: CheckerAction.REDUCE, number: 1 },
        [RiscTokenType.REGISTER]: { type: CheckerAction.REDUCE, number: 1 },
        [RiscTokenType.LABEL]: { type: CheckerAction.REDUCE, number: 1 },
        [RiscTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [RiscTokenType.ARGUMENTS]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [RiscTokenType.OTHER]: { type: CheckerAction.REDUCE, number: 1 },
    },
    [RiscSyntaxState.IMM_LOAD_OPERATION]: {
        [RiscTokenType.NO_ARGS]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.TWO_REG]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.THREE_REG]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.JUMP]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.IMM_LOAD]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.STORE]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.LOAD]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.NUMBER]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.REGISTER]: { type: CheckerAction.SHIFT, number: RiscSyntaxState.IMM_LOAD_REG },
        [RiscTokenType.LABEL]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [RiscTokenType.ARGUMENTS]: { type: CheckerAction.SHIFT, number: RiscSyntaxState.OPERATION_REDUCE },
        [RiscTokenType.OTHER]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
    },
    [RiscSyntaxState.IMM_LOAD_REG]: {
        [RiscTokenType.NO_ARGS]: { type: CheckerAction.ERROR, message: LDI_IMMEDIATE },
        [RiscTokenType.TWO_REG]: { type: CheckerAction.ERROR, message: LDI_IMMEDIATE },
        [RiscTokenType.THREE_REG]: { type: CheckerAction.ERROR, message: LDI_IMMEDIATE },
        [RiscTokenType.JUMP]: { type: CheckerAction.ERROR, message: LDI_IMMEDIATE },
        [RiscTokenType.IMM_LOAD]: { type: CheckerAction.ERROR, message: LDI_IMMEDIATE },
        [RiscTokenType.STORE]: { type: CheckerAction.ERROR, message: LDI_IMMEDIATE },
        [RiscTokenType.LOAD]: { type: CheckerAction.ERROR, message: LDI_IMMEDIATE },
        [RiscTokenType.NUMBER]: { type: CheckerAction.SHIFT, number: RiscSyntaxState.IMM_LOAD_NUM },
        [RiscTokenType.REGISTER]: { type: CheckerAction.ERROR, message: LDI_IMMEDIATE },
        [RiscTokenType.LABEL]: { type: CheckerAction.ERROR, message: LDI_IMMEDIATE },
        [RiscTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [RiscTokenType.ARGUMENTS]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [RiscTokenType.OTHER]: { type: CheckerAction.ERROR, message: LDI_IMMEDIATE },
    },
    [RiscSyntaxState.IMM_LOAD_NUM]: {
        [RiscTokenType.NO_ARGS]: { type: CheckerAction.REDUCE, number: 2 },
        [RiscTokenType.TWO_REG]: { type: CheckerAction.REDUCE, number: 2 },
        [RiscTokenType.THREE_REG]: { type: CheckerAction.REDUCE, number: 2 },
        [RiscTokenType.JUMP]: { type: CheckerAction.REDUCE, number: 2 },
        [RiscTokenType.IMM_LOAD]: { type: CheckerAction.REDUCE, number: 2 },
        [RiscTokenType.STORE]: { type: CheckerAction.REDUCE, number: 2 },
        [RiscTokenType.LOAD]: { type: CheckerAction.REDUCE, number: 2 },
        [RiscTokenType.NUMBER]: { type: CheckerAction.REDUCE, number: 2 },
        [RiscTokenType.REGISTER]: { type: CheckerAction.REDUCE, number: 2 },
        [RiscTokenType.LABEL]: { type: CheckerAction.REDUCE, number: 2 },
        [RiscTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [RiscTokenType.ARGUMENTS]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [RiscTokenType.OTHER]: { type: CheckerAction.REDUCE, number: 2 },
    },
    [RiscSyntaxState.STORE_OPERATION]: {
        [RiscTokenType.NO_ARGS]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.TWO_REG]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.THREE_REG]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.JUMP]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.IMM_LOAD]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.STORE]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.LOAD]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.NUMBER]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.REGISTER]: { type: CheckerAction.SHIFT, number: RiscSyntaxState.STORE_FIRST_REG },
        [RiscTokenType.LABEL]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [RiscTokenType.ARGUMENTS]: { type: CheckerAction.SHIFT, number: RiscSyntaxState.OPERATION_REDUCE },
        [RiscTokenType.OTHER]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
    },
    [RiscSyntaxState.STORE_FIRST_REG]: {
        [RiscTokenType.NO_ARGS]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.TWO_REG]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.THREE_REG]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.JUMP]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.IMM_LOAD]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.STORE]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.LOAD]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.NUMBER]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.REGISTER]: { type: CheckerAction.SHIFT, number: RiscSyntaxState.STORE_SECOND_REG },
        [RiscTokenType.LABEL]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [RiscTokenType.ARGUMENTS]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [RiscTokenType.OTHER]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
    },
    [RiscSyntaxState.STORE_SECOND_REG]: {
        [RiscTokenType.NO_ARGS]: { type: CheckerAction.REDUCE, number: 2 },
        [RiscTokenType.TWO_REG]: { type: CheckerAction.REDUCE, number: 2 },
        [RiscTokenType.THREE_REG]: { type: CheckerAction.REDUCE, number: 2 },
        [RiscTokenType.JUMP]: { type: CheckerAction.REDUCE, number: 2 },
        [RiscTokenType.IMM_LOAD]: { type: CheckerAction.REDUCE, number: 2 },
        [RiscTokenType.STORE]: { type: CheckerAction.REDUCE, number: 2 },
        [RiscTokenType.LOAD]: { type: CheckerAction.REDUCE, number: 2 },
        [RiscTokenType.NUMBER]: { type: CheckerAction.REDUCE, number: 2 },
        [RiscTokenType.REGISTER]: { type: CheckerAction.REDUCE, number: 2 },
        [RiscTokenType.LABEL]: { type: CheckerAction.REDUCE, number: 2 },
        [RiscTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [RiscTokenType.ARGUMENTS]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [RiscTokenType.OTHER]: { type: CheckerAction.REDUCE, number: 2 },
    },
    [RiscSyntaxState.LOAD_OPERATION]: {
        [RiscTokenType.NO_ARGS]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.TWO_REG]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.THREE_REG]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.JUMP]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.IMM_LOAD]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.STORE]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.LOAD]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.NUMBER]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.REGISTER]: { type: CheckerAction.SHIFT, number: RiscSyntaxState.LOAD_FIRST_REG },
        [RiscTokenType.LABEL]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [RiscTokenType.ARGUMENTS]: { type: CheckerAction.SHIFT, number: RiscSyntaxState.OPERATION_REDUCE },
        [RiscTokenType.OTHER]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
    },
    [RiscSyntaxState.LOAD_FIRST_REG]: {
        [RiscTokenType.NO_ARGS]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.TWO_REG]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.THREE_REG]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.JUMP]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.IMM_LOAD]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.STORE]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.LOAD]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.NUMBER]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.REGISTER]: { type: CheckerAction.SHIFT, number: RiscSyntaxState.LOAD_SECOND_REG },
        [RiscTokenType.LABEL]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [RiscTokenType.ARGUMENTS]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [RiscTokenType.OTHER]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
    },
    [RiscSyntaxState.LOAD_SECOND_REG]: {
        [RiscTokenType.NO_ARGS]: { type: CheckerAction.REDUCE, number: 2 },
        [RiscTokenType.TWO_REG]: { type: CheckerAction.REDUCE, number: 2 },
        [RiscTokenType.THREE_REG]: { type: CheckerAction.REDUCE, number: 2 },
        [RiscTokenType.JUMP]: { type: CheckerAction.REDUCE, number: 2 },
        [RiscTokenType.IMM_LOAD]: { type: CheckerAction.REDUCE, number: 2 },
        [RiscTokenType.STORE]: { type: CheckerAction.REDUCE, number: 2 },
        [RiscTokenType.LOAD]: { type: CheckerAction.REDUCE, number: 2 },
        [RiscTokenType.NUMBER]: { type: CheckerAction.REDUCE, number: 2 },
        [RiscTokenType.REGISTER]: { type: CheckerAction.REDUCE, number: 2 },
        [RiscTokenType.LABEL]: { type: CheckerAction.REDUCE, number: 2 },
        [RiscTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [RiscTokenType.ARGUMENTS]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [RiscTokenType.OTHER]: { type: CheckerAction.REDUCE, number: 2 },
    },
    [RiscSyntaxState.TWO_REG_FIRST_REG]: {
        [RiscTokenType.NO_ARGS]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.TWO_REG]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.THREE_REG]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.JUMP]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.IMM_LOAD]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.STORE]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.LOAD]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.NUMBER]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.REGISTER]: { type: CheckerAction.SHIFT, number: RiscSyntaxState.TWO_REG_SECOND_REG },
        [RiscTokenType.LABEL]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [RiscTokenType.ARGUMENTS]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [RiscTokenType.OTHER]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
    },
    [RiscSyntaxState.TWO_REG_SECOND_REG]: {
        [RiscTokenType.NO_ARGS]: { type: CheckerAction.REDUCE, number: 2 },
        [RiscTokenType.TWO_REG]: { type: CheckerAction.REDUCE, number: 2 },
        [RiscTokenType.THREE_REG]: { type: CheckerAction.REDUCE, number: 2 },
        [RiscTokenType.JUMP]: { type: CheckerAction.REDUCE, number: 2 },
        [RiscTokenType.IMM_LOAD]: { type: CheckerAction.REDUCE, number: 2 },
        [RiscTokenType.STORE]: { type: CheckerAction.REDUCE, number: 2 },
        [RiscTokenType.LOAD]: { type: CheckerAction.REDUCE, number: 2 },
        [RiscTokenType.NUMBER]: { type: CheckerAction.REDUCE, number: 2 },
        [RiscTokenType.REGISTER]: { type: CheckerAction.REDUCE, number: 2 },
        [RiscTokenType.LABEL]: { type: CheckerAction.REDUCE, number: 2 },
        [RiscTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [RiscTokenType.ARGUMENTS]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [RiscTokenType.OTHER]: { type: CheckerAction.REDUCE, number: 2 },
    },
    [RiscSyntaxState.THREE_REG_FIRST_REG]: {
        [RiscTokenType.NO_ARGS]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.TWO_REG]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.THREE_REG]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.JUMP]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.IMM_LOAD]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.STORE]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.LOAD]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.NUMBER]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.REGISTER]: { type: CheckerAction.SHIFT, number: RiscSyntaxState.THREE_REG_SECOND_REG },
        [RiscTokenType.LABEL]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [RiscTokenType.ARGUMENTS]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [RiscTokenType.OTHER]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
    },
    [RiscSyntaxState.THREE_REG_SECOND_REG]: {
        [RiscTokenType.NO_ARGS]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.TWO_REG]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.THREE_REG]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.JUMP]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.IMM_LOAD]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.STORE]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.LOAD]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.NUMBER]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.REGISTER]: { type: CheckerAction.SHIFT, number: RiscSyntaxState.THREE_REG_THIRD_REG },
        [RiscTokenType.LABEL]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
        [RiscTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [RiscTokenType.ARGUMENTS]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [RiscTokenType.OTHER]: { type: CheckerAction.ERROR, message: OPERATION_REGISTER },
    },
    [RiscSyntaxState.THREE_REG_THIRD_REG]: {
        [RiscTokenType.NO_ARGS]: { type: CheckerAction.REDUCE, number: 3 },
        [RiscTokenType.TWO_REG]: { type: CheckerAction.REDUCE, number: 3 },
        [RiscTokenType.THREE_REG]: { type: CheckerAction.REDUCE, number: 3 },
        [RiscTokenType.JUMP]: { type: CheckerAction.REDUCE, number: 3 },
        [RiscTokenType.IMM_LOAD]: { type: CheckerAction.REDUCE, number: 3 },
        [RiscTokenType.STORE]: { type: CheckerAction.REDUCE, number: 3 },
        [RiscTokenType.LOAD]: { type: CheckerAction.REDUCE, number: 3 },
        [RiscTokenType.NUMBER]: { type: CheckerAction.REDUCE, number: 3 },
        [RiscTokenType.REGISTER]: { type: CheckerAction.REDUCE, number: 3 },
        [RiscTokenType.LABEL]: { type: CheckerAction.REDUCE, number: 3 },
        [RiscTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [RiscTokenType.ARGUMENTS]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [RiscTokenType.OTHER]: { type: CheckerAction.REDUCE, number: 3 },
    },
    [RiscSyntaxState.NO_ARGS_OPERATION]: {
        [RiscTokenType.NO_ARGS]: { type: CheckerAction.REDUCE, number: 0 },
        [RiscTokenType.TWO_REG]: { type: CheckerAction.REDUCE, number: 0 },
        [RiscTokenType.THREE_REG]: { type: CheckerAction.REDUCE, number: 0 },
        [RiscTokenType.JUMP]: { type: CheckerAction.REDUCE, number: 0 },
        [RiscTokenType.IMM_LOAD]: { type: CheckerAction.REDUCE, number: 0 },
        [RiscTokenType.STORE]: { type: CheckerAction.REDUCE, number: 0 },
        [RiscTokenType.LOAD]: { type: CheckerAction.REDUCE, number: 0 },
        [RiscTokenType.NUMBER]: { type: CheckerAction.REDUCE, number: 0 },
        [RiscTokenType.REGISTER]: { type: CheckerAction.REDUCE, number: 0 },
        [RiscTokenType.LABEL]: { type: CheckerAction.REDUCE, number: 0 },
        [RiscTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [RiscTokenType.ARGUMENTS]: { type: CheckerAction.SHIFT, number: RiscSyntaxState.OPERATION_REDUCE },
        [RiscTokenType.OTHER]: { type: CheckerAction.REDUCE, number: 0 },
    },
};