import { CheckerAction, type SyntaxTableEntry } from "@src/interface/visitor/SyntaxChecker";
import { ComposedTokenType, TokenType } from "@src/interface/visitor/Token";
import { AccumulatorSyntaxState } from "./SyntaxCheckerState";
import { ADDITIONAL_TOKEN, LOGIC_ERROR, NO_TEXT_LABEL } from "./ErrorAndWarning";

export const SYNTAX_TABLE_ACC: Array<Record<TokenType | ComposedTokenType, SyntaxTableEntry>> = [
    {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.LABEL]: { type: CheckerAction.ERROR, message: NO_TEXT_LABEL },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.SHIFT, number: AccumulatorSyntaxState.TEXT_INITIAL },
        [TokenType.DATA_LABEL]: { type: CheckerAction.ERROR, message: NO_TEXT_LABEL },
        [TokenType.NUMBER]: { type: CheckerAction.ERROR, message: NO_TEXT_LABEL },
        [TokenType.OPERATION]: { type: CheckerAction.ERROR, message: NO_TEXT_LABEL },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.WORD]: { type: CheckerAction.ERROR, message: NO_TEXT_LABEL },
        [ComposedTokenType.DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.SHIFT, number: AccumulatorSyntaxState.COMPLETE_PROGRAM },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT]: { type: CheckerAction.SHIFT, number: AccumulatorSyntaxState.DATA_INITIAL },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.NO_ARGS_OPERATION]: { type: CheckerAction.ERROR, message: NO_TEXT_LABEL },
    },
    {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.LABEL]: { type: CheckerAction.ERROR, message: ADDITIONAL_TOKEN },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.ERROR, message: ADDITIONAL_TOKEN },
        [TokenType.DATA_LABEL]: { type: CheckerAction.ERROR, message: ADDITIONAL_TOKEN },
        [TokenType.NUMBER]: { type: CheckerAction.ERROR, message: ADDITIONAL_TOKEN },
        [TokenType.OPERATION]: { type: CheckerAction.ERROR, message: ADDITIONAL_TOKEN },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.WORD]: { type: CheckerAction.ERROR, message: ADDITIONAL_TOKEN },
        [ComposedTokenType.DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR, },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR, },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR, },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.ERROR, message: LOGIC_ERROR, },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR, },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR, },
        [ComposedTokenType.TEXT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR, },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR, },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.ACCEPT, },
        [TokenType.NO_ARGS_OPERATION]: { type: CheckerAction.ERROR, message: ADDITIONAL_TOKEN },
    },
    {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR, },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR, },
        [TokenType.LABEL]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.PROGRAM_DATA },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.PROGRAM_DATA },
        [TokenType.DATA_LABEL]: { type: CheckerAction.SHIFT, number: AccumulatorSyntaxState.DATA_BLOCK },
        [TokenType.NUMBER]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.PROGRAM_DATA },
        [TokenType.OPERATION]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.PROGRAM_DATA },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, message: LOGIC_ERROR, },
        [TokenType.WORD]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.PROGRAM_DATA },
        [ComposedTokenType.DATA]: { type: CheckerAction.SHIFT, number: AccumulatorSyntaxState.DATA_PRESENT },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR, },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR, },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.ERROR, message: LOGIC_ERROR, },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.SHIFT, number: AccumulatorSyntaxState.DATA_REDUCTION },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR, },
        [ComposedTokenType.TEXT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR, },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR, },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.PROGRAM_DATA },
        [TokenType.NO_ARGS_OPERATION]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.PROGRAM_DATA },
    },
    {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.LABEL]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.PROGRAM },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.PROGRAM },
        [TokenType.DATA_LABEL]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.PROGRAM },
        [TokenType.NUMBER]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.PROGRAM },
        [TokenType.OPERATION]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.PROGRAM },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.WORD]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.PROGRAM },
        [ComposedTokenType.DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.PROGRAM },
        [TokenType.NO_ARGS_OPERATION]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.PROGRAM },
    },
    {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.LABEL]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.PROGRAM_DATA },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.PROGRAM_DATA },
        [TokenType.DATA_LABEL]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.PROGRAM_DATA },
        [TokenType.NUMBER]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.PROGRAM_DATA },
        [TokenType.OPERATION]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.PROGRAM_DATA },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.WORD]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.PROGRAM_DATA },
        [ComposedTokenType.DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.PROGRAM_DATA },
        [TokenType.NO_ARGS_OPERATION]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.PROGRAM_DATA },
    },
    {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.LABEL]: { type: CheckerAction.SHIFT, number: AccumulatorSyntaxState.DATA_LABEL_INIT },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [TokenType.DATA_LABEL]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [TokenType.NUMBER]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [TokenType.OPERATION]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.WORD]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [ComposedTokenType.DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.SHIFT, number: AccumulatorSyntaxState.DATA_END },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [TokenType.NO_ARGS_OPERATION]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.DATA_BLOCK },
    },
    {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.LABEL]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.DATA_LABEL]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.NUMBER]: { type: CheckerAction.SHIFT, number: AccumulatorSyntaxState.DATA_NUMBER },
        [TokenType.OPERATION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.WORD]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.NO_ARGS_OPERATION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
    },
    {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.LABEL]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.DATA },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.DATA },
        [TokenType.DATA_LABEL]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.DATA },
        [TokenType.NUMBER]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.DATA },
        [TokenType.OPERATION]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.DATA },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.WORD]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.DATA },
        [ComposedTokenType.DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.DATA },
        [TokenType.NO_ARGS_OPERATION]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.DATA },
    },
    {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.LABEL]: { type: CheckerAction.SHIFT, number: AccumulatorSyntaxState.DATA_LABEL_INIT },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [TokenType.DATA_LABEL]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [TokenType.NUMBER]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [TokenType.OPERATION]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.WORD]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [ComposedTokenType.DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.SHIFT, number: AccumulatorSyntaxState.COMPLETE_DATA_LABEL },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [TokenType.NO_ARGS_OPERATION]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.DATA_BLOCK },
    },
    {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.LABEL]: { type: CheckerAction.REDUCE, number: 3, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.REDUCE, number: 3, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [TokenType.DATA_LABEL]: { type: CheckerAction.REDUCE, number: 3, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [TokenType.NUMBER]: { type: CheckerAction.REDUCE, number: 3, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [TokenType.OPERATION]: { type: CheckerAction.REDUCE, number: 3, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.WORD]: { type: CheckerAction.REDUCE, number: 3, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [ComposedTokenType.DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.REDUCE, number: 3, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [TokenType.NO_ARGS_OPERATION]: { type: CheckerAction.REDUCE, number: 3, reducedAddition: ComposedTokenType.DATA_BLOCK },
    },
    {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.LABEL]: { type: CheckerAction.SHIFT, number: AccumulatorSyntaxState.REDUCE_LABEL },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.TEXT_BLOCK },
        [TokenType.DATA_LABEL]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.TEXT_BLOCK },
        [TokenType.NUMBER]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.TEXT_BLOCK },
        [TokenType.OPERATION]: { type: CheckerAction.SHIFT, number: AccumulatorSyntaxState.DETECT_OPERATION },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.WORD]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.TEXT_BLOCK },
        [ComposedTokenType.DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.SHIFT, number: AccumulatorSyntaxState.REDUCE_INST },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.SHIFT, number: AccumulatorSyntaxState.TEXT_BLOCK },
        [ComposedTokenType.TEXT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.SHIFT, number: AccumulatorSyntaxState.TEXT_END },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.TEXT_BLOCK },
        [TokenType.NO_ARGS_OPERATION]: { type: CheckerAction.SHIFT, number: AccumulatorSyntaxState.DETECT_SIMPLE_OPERATION },
    },
    {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.LABEL]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.TEXT },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.TEXT },
        [TokenType.DATA_LABEL]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.TEXT },
        [TokenType.NUMBER]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.TEXT },
        [TokenType.OPERATION]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.TEXT },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.WORD]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.TEXT },
        [ComposedTokenType.DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.TEXT },
        [TokenType.NO_ARGS_OPERATION]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.TEXT },
    },
    {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.LABEL]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.STATEMENT },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.STATEMENT },
        [TokenType.DATA_LABEL]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.STATEMENT },
        [TokenType.NUMBER]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.STATEMENT },
        [TokenType.OPERATION]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.STATEMENT },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.WORD]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.STATEMENT },
        [ComposedTokenType.DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.STATEMENT },
        [TokenType.NO_ARGS_OPERATION]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.STATEMENT },
    },
    {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.LABEL]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.STATEMENT },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.STATEMENT },
        [TokenType.DATA_LABEL]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.STATEMENT },
        [TokenType.NUMBER]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.STATEMENT },
        [TokenType.OPERATION]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.STATEMENT },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.WORD]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.STATEMENT },
        [ComposedTokenType.DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.STATEMENT },
        [TokenType.NO_ARGS_OPERATION]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.STATEMENT },
    },
    {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.LABEL]: { type: CheckerAction.ERROR },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.ERROR },
        [TokenType.DATA_LABEL]: { type: CheckerAction.ERROR },
        [TokenType.NUMBER]: { type: CheckerAction.ERROR },
        [TokenType.OPERATION]: { type: CheckerAction.ERROR },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.WORD]: { type: CheckerAction.SHIFT, number: AccumulatorSyntaxState.OPERATION_ADDRESS },
        [ComposedTokenType.DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.ERROR },
        [TokenType.NO_ARGS_OPERATION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
    },
    {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.LABEL]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.INSTRUCTION },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.INSTRUCTION },
        [TokenType.DATA_LABEL]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.INSTRUCTION },
        [TokenType.NUMBER]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.INSTRUCTION },
        [TokenType.OPERATION]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.INSTRUCTION },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.WORD]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.INSTRUCTION },
        [ComposedTokenType.DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.INSTRUCTION },
        [TokenType.NO_ARGS_OPERATION]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.INSTRUCTION },
    },
    {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.LABEL]: { type: CheckerAction.SHIFT, number: AccumulatorSyntaxState.REDUCE_LABEL },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.TEXT_BLOCK },
        [TokenType.DATA_LABEL]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.TEXT_BLOCK },
        [TokenType.NUMBER]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.TEXT_BLOCK },
        [TokenType.OPERATION]: { type: CheckerAction.SHIFT, number: AccumulatorSyntaxState.DETECT_OPERATION },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.WORD]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.TEXT_BLOCK },
        [ComposedTokenType.DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.SHIFT, number: AccumulatorSyntaxState.REDUCE_INST },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.SHIFT, number: AccumulatorSyntaxState.TEXT_BLOCK },
        [ComposedTokenType.TEXT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.SHIFT, number: AccumulatorSyntaxState.STATEMENT_REDUCTION, },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.TEXT_BLOCK },
        [TokenType.NO_ARGS_OPERATION]: { type: CheckerAction.SHIFT, number: 18 },
    },
    {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.LABEL]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.TEXT_BLOCK },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.TEXT_BLOCK },
        [TokenType.DATA_LABEL]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.TEXT_BLOCK },
        [TokenType.NUMBER]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.TEXT_BLOCK },
        [TokenType.OPERATION]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.TEXT_BLOCK },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.WORD]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.TEXT_BLOCK },
        [ComposedTokenType.DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.TEXT_BLOCK },
        [TokenType.NO_ARGS_OPERATION]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.TEXT_BLOCK },
    },
    {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.LABEL]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.INSTRUCTION },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.INSTRUCTION },
        [TokenType.DATA_LABEL]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.INSTRUCTION },
        [TokenType.NUMBER]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.INSTRUCTION },
        [TokenType.OPERATION]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.INSTRUCTION },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.WORD]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.INSTRUCTION },
        [ComposedTokenType.DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.INSTRUCTION },
        [TokenType.NO_ARGS_OPERATION]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.INSTRUCTION },
    },
];