name: Test et assurance qualité

on: [push]
jobs:
    install:
        name: Installation des dépendances node
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Installation node
              uses: actions/setup-node@v4
              with:
                node-version: '22'
            - run: cd frontend
            - run: ls -la
            - name: Installation des dépendances
              run: npm ci