name: Test et assurance qualité

on: [push]
jobs:
    install:
        name: Installation des dépendances node
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Installation node
              uses: actions/setup-node@v4
              with:
                node-version: '22'
            - name: Installation des dépendances
              working-directory: ./frontend
              run: npm ci
    lint:
        name: Vérifier les erreurs de linting
        runs-on: ubuntu-latest
        needs: install
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Installation node
              uses: actions/setup-node@v4
              with:
                node-version: '22'
            - name: Vérfication
              working-directory: ./frontend
              run: ls -la