name: Construction de l'installateur

on: [push]
jobs: 
    build-backend:
        name: Construction du backend
        runs-on: ubuntu-latest
        steps:
            - name: Installer sdkman
              working-directory: ./backend
              run: curl -s "https://get.sdkman.io" | bash
