name: Construction de l'installateur

on: [push]
jobs:
    build-backend:
        defaults:
            run:
                shell: bash -ieo pipefail {0}
        name: Construction du backend
        runs-on: ubuntu-latest
        steps:
            - name: Récupérer le code
              uses: actions/checkout@v4

            - name: Installer sdkman
              run: |
                curl -s "https://get.sdkman.io" | bash
                source "/home/runner/.sdkman/bin/sdkman-init.sh"

            - name: Installer java 
              run: sdk install java 17.0.10-tem

            - name: Installer sbt
              run: sdk install sbt

            - name: Compiler le jar
              working-directory: ./backend
              run: sbt assembly

            - name: Artéfacter le jar
              uses: actions/upload-artifact@v4
              with:
                name: backend-build
                path: ./backend/target/scala-2.12/Accumulator_CPU_Chisel-assembly-0.1.0.jar