name: Construction de l'installateur

on: [push]
jobs: 
    build-backend:
        name: Construction du backend
        runs-on: ubuntu-latest
        steps:
            - name: Installer sdkman
              run: curl -s "https://get.sdkman.io" | bash
            - name: Faire le lien avec sdkman
              run: source "/home/runner/.sdkman/bin/sdkman-init.sh"
            - name: Essaie sdk
              run: sdk help
