name: Construction de l'installateur

on: [push]
jobs:
    build-backend:
        name: Construction du backend
        runs-on: ubuntu-latest
        steps:
            - name: Installer sdkman
              run: |
                curl -s "https://get.sdkman.io" | bash
            - name: Installer java 
              run: |
                source "/home/runner/.sdkman/bin/sdkman-init.sh"
                sdk install java 17.0.10-tem
            - name: Installer sbt
              run: |
                source "/home/runner/.sdkman/bin/sdkman-init.sh"
                sdk install sbt
            - name: Obtenir le build
              working-directory: backend
              run: |
                source "/home/runner/.sdkman/bin/sdkman-init.sh"
                sbt assembly